[package]
name = "csv-to-anki"
version = "0.1.0"
edition = "2024"

[dependencies]
csv-partitioner = { git = "https://github.com/Lindamust/csv-partitioner"}
csv = "1.3.1"
serde = "1.0.228"
reqwest = "0.12.23"
